### ISSUE TITLE
Ubuntu 12.10, everpad not starting

### ISSUE THREAD

**Issue by wagafo** [nvbn/everpad#265]
Everpad 2.5.0
Just updated and restarted the desktop session just in case.

When I start everpad from the command line I get the following error:

Traceback (most recent call last):
  File "/usr/bin/everpad", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2815, in <module>
    working_set.require(**requires**)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 690, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 588, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: py-oauth2

**Comment by jenshnielsen** [comment]
I'm seeing this issue too

**Comment by nvbn** [comment]
Try to update to latest version.
This bug #261 and it fixed.

**Comment by wagafo** [comment]
OK, I just updated, now if I enter just enter "everpad" at the comand line it opens, it shows the icon in the upper panel, but the icon does not show any notes and two options are shown, "Please perform first sync" and "Settings and Management". In setting and management it shows that I'm authorized, but clicking on "Pleae performa first sync" does nothing. 

If I enter "everpad OPEN" at the command line I get:

raceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.5dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 309, in main
    app.indicator.create(args.attachments)
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 157, in create
    self.app.provider.create_note(note_struct),
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 32, in wrapper
    return getattr(self.**interface, name)(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, *_keywords)
  File "/usr/lib/pymodules/python2.7/everpad/provider/service.py", line 268, in create_note
    dbus_note.give_to_obj(note)
  File "/usr/lib/pymodules/python2.7/everpad/basetypes.py", line 55, in give_to_obj
    setattr(obj, field[0], val)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 155, in **set**
    instance_dict(instance), value, None)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 697, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 717, in fire_replace_event
    value = fn(state, value, previous, initiator or self)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 992, in emit_backref_from_scalar_set_event
    child_state, child_dict = instance_state(child),\
AttributeError: 'dbus.Int32' object has no attribute '_sa_instance_state'

**Comment by nvbn** [comment]
Why you enter "everpad OPEN"?
For starting everpad from terminal you need:

```
everpad
```

**Comment by wagafo** [comment]
OK, sorry, I still haven't used everpad (just migrating from tomboy to everpad). So, everpad starts OK, but when I click on "Please sync for the first time" nothing happens. Then I figured out that it works by clicking with the right bottom of the mouse, but not with the left buttom. After clicking with the right bottom everything OK, it has synced and I can see the note that I have created to at the web interface to start working and everything seems right.

**Comment by wagafo** [comment]
In another computer, a desktop behind a proxy which otherwise works well defined in System Settings -> Network in Ubuntu 12.10, I get a crash after clicking "Please sync for the first time". I get a "crash" report", and the end I can read the following lines, which makes me think that this is proxy related:

File "/usr/lib/pymodules/python2.7/thrift/transport/THttpClient.py", line 72, in **init**
     raise ValueError("Unsupported Proxy Scheme, %s" % http_proxy.scheme)
 ValueError: Unsupported Proxy Scheme, https
UserGroups: adm admin audio cdrom dialout lp lpadmin plugdev sambashare video www-data

**Comment by wagafo** [comment]
This seems related to this issue:

https://github.com/nvbn/everpad/issues/214

But I tried what it is suggested there, set up an environment variable https_proxy to my proxy, and start everpad, and it didn't work for me.

**Comment by wagafo** [comment]
Today I brought my laptop, which I had first synced from my home where there is no proxy, and it works perfectly behind the proxy, so it seems the problem is for the first sync. Unfortunately I cannot bring my desktop out of the proxy to do this first sync.
